packages:
  - "locald-dashboard"
  - "locald-docs"
  - "examples/**"
  # Future-proofing for the planned repo layout refactor
  - "e2e/**"

  # Common excludes
  - "!**/node_modules/**"
  - "!**/build/**"
  - "!**/dist/**"
  - "!**/target/**"
