packages:
  - locald-dashboard
  - locald-docs
  - examples/**
  - e2e/**
  - '!**/node_modules/**'
  - '!**/build/**'
  - '!**/dist/**'
  - '!**/target/**'

ignoredBuiltDependencies:
  - esbuild
  - sharp

onlyBuiltDependencies:
  - lefthook
